
spring:
  application:
    name: security
  datasource:
    url: 'jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8'
    username: root
    password: root
  jpa:
    #show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  security:
    enabled: false
